# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
## Not for grading

## Learning Objective

The objective of this experiment is to understand Linear classifier.

## Dataset

### Description

The dataset consists of the below 7 columns,

- **species:** penguin species (Chinstrap, Adélie, or Gentoo)
- **culmen length & depth:** The culmen is the upper ridge of a bird's beak
- **flipper_length_mm:** flipper length
- **body_mass_g:** body mass
- **island:** island name (Dream, Torgersen, or Biscoe)
- **sex:** penguin sex

## Setup Steps

In [1]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2418580" #@param {type:"string"}

In [2]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "9898989865" #@param {type:"string"}

In [3]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "Demo_LC_Penguins_data" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget -qq https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Penguin.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")

Setup completed successfully

## Import required packages

In [4]:
from sklearn.linear_model import SGDClassifier
import pandas as pd

## Load the data

In [5]:
dataset = "Penguin.csv"

data = pd.read_csv(dataset)

print(data.shape)

(344, 7)

In [6]:
data.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [7]:
# Count NaN values in each column of the dataframe
data.isna().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [8]:
# Print the unique() elements from the sex column
data['sex'].unique()

array(['MALE', 'FEMALE', nan], dtype=object)

In [9]:
# Drop the records where sex column has NaN values
data.dropna(subset = ['sex'], inplace = True)

# Print the unique() elements from the sex column after dropping
print("Unique values after dropping NA values : ", data.sex.unique())

Unique values after dropping NA values :  ['MALE' 'FEMALE']

In [10]:
data['species'] = data['species'].replace(['Adelie', 'Chinstrap', 'Gentoo'],[0, 1, 2])
data['island'] = data['island'].replace(['Torgersen', 'Biscoe', 'Dream'],[2, 1, 0])
data['sex'] = data['sex'].replace(['MALE', 'FEMALE'],[1, 0])

<ipython-input-10-3b9f592d4c42>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['species'] = data['species'].replace(['Adelie', 'Chinstrap', 'Gentoo'],[0, 1, 2])
<ipython-input-10-3b9f592d4c42>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['island'] = data['island'].replace(['Torgersen', 'Biscoe', 'Dream'],[2, 1, 0])
<ipython-input-10-3b9f592d4c42>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['sex'] = data['sex'].replace(['MALE', 'FEMALE'],[1, 0])

In [11]:
data.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,2,39.1,18.7,181.0,3750.0,1
1,0,2,39.5,17.4,186.0,3800.0,0
2,0,2,40.3,18.0,195.0,3250.0,0
4,0,2,36.7,19.3,193.0,3450.0,0
5,0,2,39.3,20.6,190.0,3650.0,1

## Store the data and labels

In [12]:
X = data.drop(['species'], axis=1)
y = data['species']

## Split the data into train and test sets

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [15]:
# The size of train and test sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((233, 6), (100, 6), (233,), (100,))

## Train a  Linear Classifier

In [16]:
linear_classifier = SGDClassifier()

# Train or fit the model with the train data
linear_classifier.fit(X_train, y_train)

# Test the trained model
y_pred = linear_classifier.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, y_test))

0.34

## Scaling the data

In [18]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scale1 = scaler.fit_transform(X_train)
X_test_scale1 = scaler.transform(X_test)

linear_classifier = SGDClassifier()

# Train or fit the model with the train data
linear_classifier.fit(X_train_scale1, y_train)

# Test the trained model
y_pred_scale = linear_classifier.predict(X_test_scale1)

print(accuracy_score(y_pred_scale, y_test))

0.98

In [19]:
print(X_train_scale1)

[[ 0.38815646 -0.68859414  0.41178581 -1.01319331 -1.22511852 -0.99571733]
 [ 0.38815646  0.75514402 -0.77912631  1.44365316  1.10435628  1.0043011 ]
 [ 0.38815646  0.60514525 -1.29691419  0.79331144  0.64459151 -0.99571733]
 ...
 [ 0.38815646 -0.83859291  0.30822823 -0.57963217 -1.22511852 -0.99571733]
 [ 0.38815646  0.24889817 -1.08979904  1.37139297  0.98175234  1.0043011 ]
 [ 0.38815646 -1.13859045 -0.05422328 -1.44675445 -1.25576951 -0.99571733]]

In [20]:
print(linear_classifier.predict([[0.38815646,-0.68859414, 0.41178581, -1.01319331, -1.22511852, -0.99571733]]))

[0]

## Please answer the questions below to complete the experiment:

In [21]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

In [22]:
#@title If it was very easy, what more you would have liked to have been added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "d\"sad\"smore you\" would have liked to have been added? If it was very \"difficult, what would you have liked to have been removed? [ ] Additional:" #@param {type:"string"}

In [23]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "No" #@param ["","Yes", "No"]

In [24]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Didn't use" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [25]:
#@title Run this cell to submit your notebook  { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id =return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 402
Date of submission:  21 Nov 2024
Time of submission:  06:34:40
View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions